### ISSUE TITLE
コーディング規則

### ISSUE THREAD

**Issue by 1inguini** [mitsuchi/mud#2]
リストのパターンマッチとかで`[a]`じゃなくて`a:[]`ってなってるのはこだわりがあってのことですか?
あと他にも規則みたいなのあれば教えてください(先頭の謎インデント全部消しちゃったけど)

**Comment by mitsuchi** [comment]
a:[] になってるのはこだわりとかではないです。なるほど [a] でいいですよね…。ありがとうございます。
コーディング規則も独自のこだわりみたいなのはありません。一般的なのがあればそれに従うようにしたいです。

**Comment by 1inguini** [comment]
じゃあhlintガンガンかけちゃいますね
