### ISSUE TITLE
パース時に関数定義が引数になり得る

### ISSUE THREAD

**Issue by 1inguini** [mitsuchi/mud#7]
実行時?にコケますが
```
(fun add = x y -> x + y) + (fun sub = x y -> x - y)
```
というか
```
fun add = x y -> x + y + fun sub = x y -> x - y
```
のパースが成功してしまいますが、これは弾いたほうがいいですよね?

**Comment by mitsuchi** [comment]
そうですね…。それが通って嬉しいケースってあんまりなさそうですもんね。
弾けるなら弾いた方がよさそうです。というか、いろいろと本当にありがとうございます…！

**Comment by 1inguini** [comment]
実装力がないので口出ししかしてない...:cry:
